# Generated by Django 2.2.6 on 2019-10-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='queston',
            new_name='question',
        ),
    ]
